name: clippy

on:
  push:
    branches: [ stable ]
  pull_request:
    branches: [ stable ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run clippy
      run: cargo clippy --verbose --all-features -- -D warnings
